# action.yaml
name: 'Configures Envars for Principles'
description: 'Configures environmental variables for Docker'
runs:
  using: "composite"
  steps:
    - id: configure_tag
      run: |
        BRANCH_NAME=$(echo ${{ github.ref }} | cut -d '/' -f 3- --output-delimiter='/')
        echo "SANITIZED_BRANCH_NAME=$(echo $BRANCH_NAME | tr -cd '[:alnum:]')"  >> $GITHUB_ENV
        if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
          echo 'TAG_PREFIX=v' >> $GITHUB_ENV
          echo 'DRY_RUN=false' >> $GITHUB_ENV
        else
          echo 'TAG_PREFIX='$(echo ${{env.BRANCH_NAME}} | tr -cd '[:alnum:]') >> $GITHUB_ENV
          echo 'DRY_RUN=true' >> $GITHUB_ENV
        fi
      shell: bash
    - id: save_tag
      run: |
        COMPUTED_TAG=$(echo ${{env.SANITIZED_BRANCH_NAME}}-${{ env.IMAGE_VERSION }}-${{ github.sha }})
        echo "COMPUTED_TAG=$COMPUTED_TAG" >> build_data.env
        echo "VERSION=$(echo ${{ env.IMAGE_VERSION }})" >> build_data.env
        echo "SHORT_TAG=$(echo ${{env.SANITIZED_BRANCH_NAME}}-${{ env.IMAGE_VERSION }})" >> build_data.env
        echo "DOCKER_FQIN=${DOCKER_LOGIN_SERVER}/${PROJECT_NAME}:${COMPUTED_TAG}" >> build_data.env
        cat build_data.env >> $GITHUB_ENV
      shell: bash
